services:

  nginx:
    container_name: full-symfony-template_nginx
    build: ./docker/nginx
    restart: on-failure
    volumes:
      - './:/var/www/full-symfony-template'
      - './docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf'
    ports:
      - "8080:80"
      - "443:443"
    depends_on:
      - php

  php:
    container_name: full-symfony-template_php
    build: ./docker/php
    working_dir: /var/www/full-symfony-template/
    volumes:
      - './:/var/www/full-symfony-template'

  database:
    container_name: full-symfony-template_postgresql
    build: ./docker/postgres
    ports:
      - "5432"
    environment:
      POSTGRES_DB: 'full_symfony_template'
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_USER: 'root'
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw

  mailer:
    container_name: full-symfony-template_mailer
    image: axllent/mailpit
    ports:
      - "1025"
      - "1080"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:

  database_data:
